services:
  manga-reader:
    container_name: manga-reader-v2
    build:
      context: https://github.com/koalasam/manga-reader-v2.git
    restart: unless-stopped

    ports:
      - "5000:5000"

    volumes:
      - /path/to/data:/app/data
      - /path/to/manga:/app/manga